spring:
  application:
    name: dorami
  redis:
    database: 0
    host: localhost
    port: 6379
    encode: UTF-8
    password:
    timeout: 6000

server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/